[package]
name = "upload_download_api"
version = "1.0.0"
authors = ["Tran Ky Hoa Thanh <thanhtkh@ahamove.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.21", features = ["macros", "rt-threaded", "fs"] }
warp = "0.2.3"
uuid = { version = "0.8", features = ["v4"] }
futures = { version = "=0.3.5", default-features = false }
bytes = "0.5.6"

[profile.dev]
debug = 0

[profile.test]
debug = 0

[profile.release]
panic = 'abort'
